export enum Envs {
  DB_HOST_READ_ONLY = "DB_HOST_READ_ONLY",
  DB_HOST = "DB_HOST",
  DB_USER = "DB_USER",
  DB_PASSWORD = "DB_PASSWORD",
  DB_NAME = "DB_NAME",
  BASE_URL_MS = "BASE_URL_MS",
  ENVIRONMENT = "ENVIRONMENT",
  URL_WEBHOOK_ERROR_CRITICAL_SERVICES = "URL_WEBHOOK_ERROR_CRITICAL_SERVICES",
  URL_WEBHOOK_ERROR_LOGS = "URL_WEBHOOK_ERROR_LOGS",
  API_KEY_MS = "API_KEY_MS",
  APP_NAME_MS = "APP_NAME_MS"
}

export enum Carriers {
  COORDINADORA = "COORDINADORA",
  TCC = "TCC",
  SWAYP = "SWAYP",
  ENVIA = "ENVIA",
  INTERRAPIDISIMO = "INTERRAPIDISIMO"
}
