enum Environment {
  DEV = "dev",
  QA = "qa",
  PROD = "prod",
}

enum GatewayEnum {
  MONO = "MONO",
  COBRE = "COBRE",
}

enum CurrencyEnum {
  COP = "COP",
  USD = "USD",
}

enum WithdrawalStatusEnum {
  SENT = "SENT",
  SUCCESS = "SUCCESS",
  ERROR = "ERROR",
}

enum BankIdEnum {
  BANCOLOMBIA = 1,
  BANCO_AGRARIO = 2,
  BANCO_AV_VILLAS = 3,
  BBVA = 4,
  BCSC = 5,
  BANCO_CITIBANK_COLOMBIA = 6,
  BANCO_COOPERATIVO_COOPCENTRAL = 7,
  DAVIVIENDA = 8,
  BANCO_DE_BOGOTA = 9,
  BANCO_DE_OCCIDENTE = 10,
  BANCO_FALABELLA = 11,
  BANCO_FINANDINA = 12,
  BANCO_GNB_SUDAMERIS = 13,
  ITAU_BANCO_CORPBANCA = 14,
  BANCO_MUNDO_MUJER = 15,
  BANCO_PICHINCHA_SA = 16,
  BANCO_POPULAR = 17,
  BANCO_CREDIFINANCIERA_SA = 18,
  BANCO_SERFINANZA_SA = 19,
  SCOTIABANK_COLPATRIA = 20,
  BANCOOMEVA = 21,
  J_P_MORGAN_COLOMBIA = 22,
  COOFINEP = 23,
  COTRAFA_ENTIDAD_FINANCIERA = 24,
  CFA_FINANCIERA_ANTIOQUIA = 25,
  CONFIAR = 26,
  FINANCIERA_JURISCOOOP_CF = 27,
  LULO_BANK_SA = 28,
  NEQUI = 29,
  PIBANK = 30,
  BANCO_CAJA_SOCIAL = 31,
  DAVIPLATA = 33,
  NU = 34,
  IRIS = 35,
  BANCO_W_SA = 36,
  BANCAMIA_SA = 37,
  MOVII = 38,
  UALA = 39,
  RAPPIPAY = 40,
  GLOBAL66 = 41,
  JFK_COOPERATIVA_FINANCIERA = 42,
  DALE = 43,
  EXTRANJERO = 32,
}

export {
  CurrencyEnum,
  Environment,
  GatewayEnum,
  WithdrawalStatusEnum,
  BankIdEnum,
};
